#!/bin/bash

DOTFILES=$HOME/.dotfiles

FILES=(
    "zsh/.zshrc .zshrc"
    "zsh/.zprofile .oh-my-zsh/custom/.zprofile"
    "zsh/aliases.zsh .oh-my-zsh/custom/aliases.zsh"
    "nvim/init.vim .config/nvim/init.vim"
    "tmux/.tmux.conf .tmux.conf"
    "i3/config .config/i3/config"
)

# Loop through the files and symlink them
for file in "${FILES[@]}"; do
    source_file="$DOTFILES/${file%% *}"
    target_file="$HOME/${file##* }"
    echo "Symlinking $source_file to $target_file"

    # Create symbolic links
    ln -sf "$source_file" "$target_file"

    if [ $? -ne 0 ]; then
        echo "Symlinking failed for $source_file. Check the ln command and try again."
        exit 1
    fi
done

# Check if nvim is installed
if ! command -v nvim &> /dev/null; then
    echo "Neovim is not installed. Please install it before running this script."
    exit 1
fi

# Set up Neovim plugins using Vim-Plug
nvim +PlugInstall +qall

# Install/update Tmux plugins using TPM
~/.tmux/plugins/tpm/bin/install_plugins

echo "Dotfiles setup completed."


