#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,i3,nvim,tmux,zsh,personal"
fi

if [[ -z $DOTFILES ]];then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOWFOLDERS DOTFILES=$DOTFILES $DOTFILES/install

