#!/bin/bash

sudo apt update

# Install dependencies
sudo apt install -y zsh
sudo apt install -y exa
sudo apt install -y neovim
sudo apt install -y tmux
sudo apt install -y tree
sudo apt install -y i3
sudo apt install -y stow
sudo apt install -y curl
sudo apt install -y git

# Install Oh-My-Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install Powerlevel10k theme for Oh-My-Zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"

# Install Vim-Plug for Neovim
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install TPM (Tmux Plugin Manager)
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

echo "Ubuntu dependencies setup completed."
